"""user table

Revision ID: 18f30b8553f1
Revises: 
Create Date: 2025-06-23 13:04:45.965132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f30b8553f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('message_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(length=875), nullable=False),
    sa.Column('sender', sa.VARCHAR(length=30), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('string_date', sa.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_model')
    # ### end Alembic commands ###
